version: '3'
dotenv: [.env]

vars:
  PACKAGE_IMPORT_NAME: games_sales
  PYTHON_VERSION: 3.12

tasks:
  create-venv:
    desc: Create a virtual environment
    cmds:
      - uv venv -p {{.PYTHON_VERSION}} .venv
    silent: false

  sync-dev:
    desc: Sync project dependencies with optionals
    cmds:
      - cmd /c rd /s /q .venv
      - task: create-venv
      - uv sync --extra dev

  sync-test:
    desc: Sync only test dependencies
    cmds:
      - cmd /c rd /s /q .venv
      - task: create-venv
      - uv sync --extra test
      # - call .venv\Scripts\activate && uv sync --extra test # Activate and sync

  lint:
    desc: Run pre-commit hooks
    cmds:
      - uv run pre-commit run --all-files

  test:
    desc: Run pytest
    cmds:
      - cmd /c "pytest -v -s -ra"

  help:
    desc: Print all tasks defined in the Taskfile
    cmd: task -l
    silent: true

  default:
    cmds:
      - task: help
    silent: true

  build:
    desc: Build the project
    cmds:
      - uv build

  dab-deploy-run:
    desc: Deploy and run on Databricks
    cmds:
      - databricks bundle validate
      - databricks bundle deploy
      - databricks bundle run

  dab-destroy:
    desc: Destroy workflow on Databricks
    cmds:
      - databricks bundle destroy
